//! Constraint events for break detection, tension reporting, and state changes.
//!
//! Events are generated during constraint solving and collected for game logic.

use glam::Vec3;
use serde::{Deserialize, Serialize};

use super::ConstraintId;

/// Events generated by the constraint solver.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum ConstraintEvent {
    /// A constraint exceeded its break threshold and was removed.
    Broke(BreakEvent),
    /// Tension information for a distance/rope constraint.
    Tension(TensionEvent),
    /// A slider/hinge reached its limit.
    LimitReached(LimitEvent),
    /// A rope became taut after being slack.
    RopeTaut(RopeTautEvent),
    /// A rope became slack after being taut.
    RopeSlack(RopeSlackEvent),
}

impl ConstraintEvent {
    /// Returns the constraint ID associated with this event.
    #[must_use]
    pub const fn constraint_id(&self) -> ConstraintId {
        match self {
            Self::Broke(e) => e.constraint_id,
            Self::Tension(e) => e.constraint_id,
            Self::LimitReached(e) => e.constraint_id,
            Self::RopeTaut(e) => e.constraint_id,
            Self::RopeSlack(e) => e.constraint_id,
        }
    }

    /// Returns whether this is a break event.
    #[must_use]
    pub const fn is_break(&self) -> bool {
        matches!(self, Self::Broke(_))
    }

    /// Returns the break event if this is one.
    #[must_use]
    pub const fn as_break(&self) -> Option<&BreakEvent> {
        match self {
            Self::Broke(e) => Some(e),
            _ => None,
        }
    }

    /// Returns the tension event if this is one.
    #[must_use]
    pub const fn as_tension(&self) -> Option<&TensionEvent> {
        match self {
            Self::Tension(e) => Some(e),
            _ => None,
        }
    }
}

/// Event emitted when a constraint breaks.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct BreakEvent {
    /// The constraint that broke.
    pub constraint_id: ConstraintId,
    /// The force that caused the break.
    pub force_magnitude: f32,
    /// The torque that caused the break (if applicable).
    pub torque_magnitude: f32,
    /// Direction of the breaking force in world space.
    pub force_direction: Vec3,
}

impl BreakEvent {
    /// Creates a break event from force.
    #[must_use]
    pub const fn from_force(
        constraint_id: ConstraintId,
        force_magnitude: f32,
        force_direction: Vec3,
    ) -> Self {
        Self {
            constraint_id,
            force_magnitude,
            torque_magnitude: 0.0,
            force_direction,
        }
    }

    /// Creates a break event from torque.
    #[must_use]
    pub const fn from_torque(constraint_id: ConstraintId, torque_magnitude: f32) -> Self {
        Self {
            constraint_id,
            force_magnitude: 0.0,
            torque_magnitude,
            force_direction: Vec3::ZERO,
        }
    }
}

/// Event reporting tension on a distance/rope constraint.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct TensionEvent {
    /// The constraint reporting tension.
    pub constraint_id: ConstraintId,
    /// Current tension magnitude (positive = pulling).
    pub tension: f32,
    /// Current distance between anchor points.
    pub current_distance: f32,
    /// Target/rest distance.
    pub target_distance: f32,
    /// Direction from endpoint A to endpoint B.
    pub direction: Vec3,
}

impl TensionEvent {
    /// Creates a new tension event.
    #[must_use]
    pub const fn new(
        constraint_id: ConstraintId,
        tension: f32,
        current_distance: f32,
        target_distance: f32,
        direction: Vec3,
    ) -> Self {
        Self {
            constraint_id,
            tension,
            current_distance,
            target_distance,
            direction,
        }
    }

    /// Returns whether the constraint is stretched beyond rest length.
    #[must_use]
    pub fn is_stretched(&self) -> bool {
        self.current_distance > self.target_distance
    }

    /// Returns the amount of stretch (negative if compressed).
    #[must_use]
    pub fn stretch_amount(&self) -> f32 {
        self.current_distance - self.target_distance
    }
}

/// Event emitted when a slider/hinge hits its limit.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct LimitEvent {
    /// The constraint that reached its limit.
    pub constraint_id: ConstraintId,
    /// Which limit was reached.
    pub limit_type: LimitType,
    /// Current position/angle value.
    pub current_value: f32,
    /// The limit value that was reached.
    pub limit_value: f32,
}

impl LimitEvent {
    /// Creates a new limit event.
    #[must_use]
    pub const fn new(
        constraint_id: ConstraintId,
        limit_type: LimitType,
        current_value: f32,
        limit_value: f32,
    ) -> Self {
        Self {
            constraint_id,
            limit_type,
            current_value,
            limit_value,
        }
    }
}

/// Type of limit reached on a constrained axis.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum LimitType {
    /// Lower position/angle limit.
    Lower,
    /// Upper position/angle limit.
    Upper,
}

/// Event emitted when a rope transitions from slack to taut.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct RopeTautEvent {
    /// The rope constraint.
    pub constraint_id: ConstraintId,
    /// Impact velocity (relative velocity when becoming taut).
    pub impact_velocity: f32,
    /// Current rope length.
    pub length: f32,
}

impl RopeTautEvent {
    /// Creates a new rope taut event.
    #[must_use]
    pub const fn new(constraint_id: ConstraintId, impact_velocity: f32, length: f32) -> Self {
        Self {
            constraint_id,
            impact_velocity,
            length,
        }
    }
}

/// Event emitted when a rope transitions from taut to slack.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct RopeSlackEvent {
    /// The rope constraint.
    pub constraint_id: ConstraintId,
    /// Slack amount (how much shorter than max length).
    pub slack_amount: f32,
}

impl RopeSlackEvent {
    /// Creates a new rope slack event.
    #[must_use]
    pub const fn new(constraint_id: ConstraintId, slack_amount: f32) -> Self {
        Self {
            constraint_id,
            slack_amount,
        }
    }
}

/// Collected events from a constraint solve step.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct ConstraintEvents {
    events: Vec<ConstraintEvent>,
}

impl ConstraintEvents {
    /// Creates an empty event collection.
    #[must_use]
    pub const fn new() -> Self {
        Self { events: Vec::new() }
    }

    /// Adds an event.
    pub fn push(&mut self, event: ConstraintEvent) {
        self.events.push(event);
    }

    /// Returns whether there are any events.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.events.is_empty()
    }

    /// Returns the number of events.
    #[must_use]
    pub fn len(&self) -> usize {
        self.events.len()
    }

    /// Returns an iterator over the events.
    pub fn iter(&self) -> impl Iterator<Item = &ConstraintEvent> {
        self.events.iter()
    }

    /// Returns all break events.
    pub fn breaks(&self) -> impl Iterator<Item = &BreakEvent> {
        self.events.iter().filter_map(ConstraintEvent::as_break)
    }

    /// Returns all tension events.
    pub fn tensions(&self) -> impl Iterator<Item = &TensionEvent> {
        self.events.iter().filter_map(ConstraintEvent::as_tension)
    }

    /// Returns IDs of constraints that broke.
    pub fn broken_constraints(&self) -> impl Iterator<Item = ConstraintId> + '_ {
        self.breaks().map(|e| e.constraint_id)
    }

    /// Clears all events.
    pub fn clear(&mut self) {
        self.events.clear();
    }

    /// Consumes and returns the inner vec.
    #[must_use]
    pub fn into_vec(self) -> Vec<ConstraintEvent> {
        self.events
    }
}

impl IntoIterator for ConstraintEvents {
    type Item = ConstraintEvent;
    type IntoIter = std::vec::IntoIter<ConstraintEvent>;

    fn into_iter(self) -> Self::IntoIter {
        self.events.into_iter()
    }
}

impl<'a> IntoIterator for &'a ConstraintEvents {
    type Item = &'a ConstraintEvent;
    type IntoIter = std::slice::Iter<'a, ConstraintEvent>;

    fn into_iter(self) -> Self::IntoIter {
        self.events.iter()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use approx::assert_relative_eq;

    #[test]
    fn break_event_from_force() {
        let event = BreakEvent::from_force(ConstraintId::new(1), 100.0, Vec3::Y);
        assert_eq!(event.constraint_id, ConstraintId::new(1));
        assert_relative_eq!(event.force_magnitude, 100.0);
        assert_relative_eq!(event.torque_magnitude, 0.0);
    }

    #[test]
    fn tension_event_stretch() {
        let event = TensionEvent::new(ConstraintId::new(2), 50.0, 5.0, 4.0, Vec3::X);
        assert!(event.is_stretched());
        assert_relative_eq!(event.stretch_amount(), 1.0);
    }

    #[test]
    fn tension_event_compressed() {
        let event = TensionEvent::new(ConstraintId::new(2), -20.0, 3.0, 4.0, Vec3::X);
        assert!(!event.is_stretched());
        assert_relative_eq!(event.stretch_amount(), -1.0);
    }

    #[test]
    fn constraint_events_collection() {
        let mut events = ConstraintEvents::new();
        assert!(events.is_empty());

        events.push(ConstraintEvent::Broke(BreakEvent::from_force(
            ConstraintId::new(1),
            100.0,
            Vec3::Y,
        )));
        events.push(ConstraintEvent::Tension(TensionEvent::new(
            ConstraintId::new(2),
            50.0,
            5.0,
            4.0,
            Vec3::X,
        )));

        assert_eq!(events.len(), 2);
        assert_eq!(events.breaks().count(), 1);
        assert_eq!(events.tensions().count(), 1);
        assert_eq!(
            events.broken_constraints().collect::<Vec<_>>(),
            vec![ConstraintId::new(1)]
        );
    }

    #[test]
    fn event_serialization() {
        let event =
            ConstraintEvent::Broke(BreakEvent::from_force(ConstraintId::new(5), 200.0, Vec3::Z));
        let json = serde_json::to_string(&event).unwrap();
        let recovered: ConstraintEvent = serde_json::from_str(&json).unwrap();
        assert_eq!(recovered.constraint_id(), ConstraintId::new(5));
        assert!(recovered.is_break());
    }

    #[test]
    fn events_into_iter() {
        let mut events = ConstraintEvents::new();
        events.push(ConstraintEvent::RopeTaut(RopeTautEvent::new(
            ConstraintId::new(1),
            2.0,
            10.0,
        )));

        let collected: Vec<_> = events.into_iter().collect();
        assert_eq!(collected.len(), 1);
    }
}
