//! Volume events for entry, exit, and state changes.

use serde::{Deserialize, Serialize};

use super::VolumeId;

/// Events generated by the volume system.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub enum VolumeEvent {
    /// An entity entered a volume.
    Entered(EntryEvent),
    /// An entity exited a volume.
    Exited(ExitEvent),
}

impl VolumeEvent {
    /// Returns the volume ID associated with this event.
    #[must_use]
    pub const fn volume_id(&self) -> VolumeId {
        match self {
            Self::Entered(e) => e.volume_id,
            Self::Exited(e) => e.volume_id,
        }
    }

    /// Returns the entity ID associated with this event.
    #[must_use]
    pub const fn entity_id(&self) -> u64 {
        match self {
            Self::Entered(e) => e.entity_id,
            Self::Exited(e) => e.entity_id,
        }
    }

    /// Returns whether this is an entry event.
    #[must_use]
    pub const fn is_entry(&self) -> bool {
        matches!(self, Self::Entered(_))
    }

    /// Returns whether this is an exit event.
    #[must_use]
    pub const fn is_exit(&self) -> bool {
        matches!(self, Self::Exited(_))
    }

    /// Returns the entry event if this is one.
    #[must_use]
    pub const fn as_entry(&self) -> Option<&EntryEvent> {
        match self {
            Self::Entered(e) => Some(e),
            Self::Exited(_) => None,
        }
    }

    /// Returns the exit event if this is one.
    #[must_use]
    pub const fn as_exit(&self) -> Option<&ExitEvent> {
        match self {
            Self::Exited(e) => Some(e),
            Self::Entered(_) => None,
        }
    }
}

/// Event emitted when an entity enters a volume.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntryEvent {
    /// The volume being entered.
    pub volume_id: VolumeId,
    /// The entity entering the volume.
    pub entity_id: u64,
    /// Entry velocity magnitude.
    pub entry_speed: f32,
    /// Penetration depth at entry.
    pub penetration: f32,
}

impl EntryEvent {
    /// Creates a new entry event.
    #[must_use]
    pub const fn new(volume_id: VolumeId, entity_id: u64) -> Self {
        Self {
            volume_id,
            entity_id,
            entry_speed: 0.0,
            penetration: 0.0,
        }
    }

    /// Builder: sets entry speed.
    #[must_use]
    pub const fn with_entry_speed(mut self, speed: f32) -> Self {
        self.entry_speed = speed;
        self
    }

    /// Builder: sets penetration depth.
    #[must_use]
    pub const fn with_penetration(mut self, depth: f32) -> Self {
        self.penetration = depth;
        self
    }
}

/// Event emitted when an entity exits a volume.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExitEvent {
    /// The volume being exited.
    pub volume_id: VolumeId,
    /// The entity exiting the volume.
    pub entity_id: u64,
    /// Total time spent in the volume (seconds).
    pub duration: f32,
    /// Exit velocity magnitude.
    pub exit_speed: f32,
}

impl ExitEvent {
    /// Creates a new exit event.
    #[must_use]
    pub const fn new(volume_id: VolumeId, entity_id: u64) -> Self {
        Self {
            volume_id,
            entity_id,
            duration: 0.0,
            exit_speed: 0.0,
        }
    }

    /// Builder: sets duration.
    #[must_use]
    pub const fn with_duration(mut self, duration: f32) -> Self {
        self.duration = duration;
        self
    }

    /// Builder: sets exit speed.
    #[must_use]
    pub const fn with_exit_speed(mut self, speed: f32) -> Self {
        self.exit_speed = speed;
        self
    }
}

/// Collected events from volume updates.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct VolumeEvents {
    events: Vec<VolumeEvent>,
}

impl VolumeEvents {
    /// Creates an empty event collection.
    #[must_use]
    pub const fn new() -> Self {
        Self { events: Vec::new() }
    }

    /// Adds an event.
    pub fn push(&mut self, event: VolumeEvent) {
        self.events.push(event);
    }

    /// Adds an entry event.
    pub fn push_entry(&mut self, event: EntryEvent) {
        self.events.push(VolumeEvent::Entered(event));
    }

    /// Adds an exit event.
    pub fn push_exit(&mut self, event: ExitEvent) {
        self.events.push(VolumeEvent::Exited(event));
    }

    /// Returns whether there are any events.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.events.is_empty()
    }

    /// Returns the number of events.
    #[must_use]
    pub fn len(&self) -> usize {
        self.events.len()
    }

    /// Returns an iterator over the events.
    pub fn iter(&self) -> impl Iterator<Item = &VolumeEvent> {
        self.events.iter()
    }

    /// Returns all entry events.
    pub fn entries(&self) -> impl Iterator<Item = &EntryEvent> {
        self.events.iter().filter_map(VolumeEvent::as_entry)
    }

    /// Returns all exit events.
    pub fn exits(&self) -> impl Iterator<Item = &ExitEvent> {
        self.events.iter().filter_map(VolumeEvent::as_exit)
    }

    /// Returns events for a specific volume.
    pub fn for_volume(&self, volume_id: VolumeId) -> impl Iterator<Item = &VolumeEvent> {
        self.events
            .iter()
            .filter(move |e| e.volume_id() == volume_id)
    }

    /// Returns events for a specific entity.
    pub fn for_entity(&self, entity_id: u64) -> impl Iterator<Item = &VolumeEvent> {
        self.events
            .iter()
            .filter(move |e| e.entity_id() == entity_id)
    }

    /// Clears all events.
    pub fn clear(&mut self) {
        self.events.clear();
    }

    /// Consumes and returns the inner vec.
    #[must_use]
    pub fn into_vec(self) -> Vec<VolumeEvent> {
        self.events
    }
}

impl IntoIterator for VolumeEvents {
    type Item = VolumeEvent;
    type IntoIter = std::vec::IntoIter<VolumeEvent>;

    fn into_iter(self) -> Self::IntoIter {
        self.events.into_iter()
    }
}

impl<'a> IntoIterator for &'a VolumeEvents {
    type Item = &'a VolumeEvent;
    type IntoIter = std::slice::Iter<'a, VolumeEvent>;

    fn into_iter(self) -> Self::IntoIter {
        self.events.iter()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use approx::assert_relative_eq;

    #[test]
    fn entry_event_builder() {
        let event = EntryEvent::new(VolumeId::new(1), 42)
            .with_entry_speed(5.0)
            .with_penetration(0.5);

        assert_eq!(event.volume_id, VolumeId::new(1));
        assert_eq!(event.entity_id, 42);
        assert_relative_eq!(event.entry_speed, 5.0);
        assert_relative_eq!(event.penetration, 0.5);
    }

    #[test]
    fn exit_event_builder() {
        let event = ExitEvent::new(VolumeId::new(2), 100)
            .with_duration(3.5)
            .with_exit_speed(2.0);

        assert_eq!(event.volume_id, VolumeId::new(2));
        assert_relative_eq!(event.duration, 3.5);
    }

    #[test]
    fn volume_event_accessors() {
        let entry = VolumeEvent::Entered(EntryEvent::new(VolumeId::new(1), 50));
        assert!(entry.is_entry());
        assert!(!entry.is_exit());
        assert!(entry.as_entry().is_some());
        assert!(entry.as_exit().is_none());

        let exit = VolumeEvent::Exited(ExitEvent::new(VolumeId::new(2), 60));
        assert!(!exit.is_entry());
        assert!(exit.is_exit());
    }

    #[test]
    fn volume_events_collection() {
        let mut events = VolumeEvents::new();
        assert!(events.is_empty());

        events.push_entry(EntryEvent::new(VolumeId::new(1), 10));
        events.push_exit(ExitEvent::new(VolumeId::new(1), 20));
        events.push_entry(EntryEvent::new(VolumeId::new(2), 10));

        assert_eq!(events.len(), 3);
        assert_eq!(events.entries().count(), 2);
        assert_eq!(events.exits().count(), 1);
    }

    #[test]
    fn filter_by_volume() {
        let mut events = VolumeEvents::new();
        events.push_entry(EntryEvent::new(VolumeId::new(1), 10));
        events.push_entry(EntryEvent::new(VolumeId::new(2), 20));
        events.push_exit(ExitEvent::new(VolumeId::new(1), 10));

        let vol1_events: Vec<_> = events.for_volume(VolumeId::new(1)).collect();
        assert_eq!(vol1_events.len(), 2);
    }

    #[test]
    fn filter_by_entity() {
        let mut events = VolumeEvents::new();
        events.push_entry(EntryEvent::new(VolumeId::new(1), 10));
        events.push_entry(EntryEvent::new(VolumeId::new(2), 10));
        events.push_entry(EntryEvent::new(VolumeId::new(1), 20));

        let entity10_events: Vec<_> = events.for_entity(10).collect();
        assert_eq!(entity10_events.len(), 2);
    }

    #[test]
    fn event_serialization() {
        let event =
            VolumeEvent::Entered(EntryEvent::new(VolumeId::new(5), 100).with_entry_speed(3.0));
        let json = serde_json::to_string(&event).unwrap();
        let recovered: VolumeEvent = serde_json::from_str(&json).unwrap();
        assert_eq!(recovered.volume_id(), VolumeId::new(5));
        assert!(recovered.is_entry());
    }

    #[test]
    fn events_into_iter() {
        let mut events = VolumeEvents::new();
        events.push_entry(EntryEvent::new(VolumeId::new(1), 1));
        events.push_exit(ExitEvent::new(VolumeId::new(1), 1));

        let collected: Vec<_> = events.into_iter().collect();
        assert_eq!(collected.len(), 2);
    }
}
